services:
  gotify:
    # Use the specific ARM64 image to run locally on my M1 MacBook
    # There is no general image with multiple Arch support...
    image: "ghcr.io/lukasknuth/gotify-slack-webhook-bundled:latest"

  test:
    build: "."
    depends_on:
      gotify:
        condition: service_started
    environment:
      GOTIFY_ENDPOINT: "http://gotify"
