# Terraform Provider testing workflow.
name: Push/PR

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
    # We only run on branch pushes. This excludes tag pushes implicitly.
    branches:
      - '**'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/_check.yml

